ALTER TABLE storefront_settings
    MODIFY COLUMN setting_value TEXT NOT NULL,
    MODIFY COLUMN value_type ENUM('int', 'string', 'boolean', 'json', 'color', 'url', 'image', 'select') NOT NULL DEFAULT 'string',
    ADD COLUMN draft_value TEXT NULL AFTER setting_value,
    ADD COLUMN updated_by INT NULL AFTER value_type,
    ADD COLUMN published_at TIMESTAMP NULL AFTER updated_by;

UPDATE storefront_settings
SET published_at = COALESCE(published_at, updated_at, CURRENT_TIMESTAMP)
WHERE published_at IS NULL;

INSERT INTO storefront_settings (setting_key, setting_value, value_type, published_at)
VALUES
    ('site_name', 'WIND OF FALL', 'string', CURRENT_TIMESTAMP),
    ('site_tagline', 'Thời trang mặc đẹp mỗi ngày', 'string', CURRENT_TIMESTAMP),
    ('brand_initials', 'WF', 'string', CURRENT_TIMESTAMP),
    ('brand_alt_text', 'WIND OF FALL', 'string', CURRENT_TIMESTAMP),
    ('logo_url', '/favicon.png', 'image', CURRENT_TIMESTAMP),
    ('admin_logo_url', '/favicon.png', 'image', CURRENT_TIMESTAMP),
    ('favicon_url', '/favicon.png', 'image', CURRENT_TIMESTAMP),
    ('brand_font_family', '''Be Vietnam Pro'', sans-serif', 'select', CURRENT_TIMESTAMP),
    ('brand_name_font_size', '18', 'int', CURRENT_TIMESTAMP),
    ('site_font_family', '''Be Vietnam Pro'', sans-serif', 'select', CURRENT_TIMESTAMP),
    ('primary_color', '#f2c94c', 'color', CURRENT_TIMESTAMP),
    ('secondary_color', '#d8a617', 'color', CURRENT_TIMESTAMP),
    ('background_color', '#fcfaf4', 'color', CURRENT_TIMESTAMP),
    ('text_color', '#18140d', 'color', CURRENT_TIMESTAMP),
    ('card_radius', '20', 'int', CURRENT_TIMESTAMP),
    ('button_radius', '999', 'int', CURRENT_TIMESTAMP),
    ('product_grid_columns', '5', 'int', CURRENT_TIMESTAMP),
    ('home_category_showcase_count', '3', 'int', CURRENT_TIMESTAMP),
    ('search_placeholder', 'Tìm áo polo, váy midi, quần jean...', 'string', CURRENT_TIMESTAMP),
    ('mobile_search_placeholder', 'Tìm sản phẩm yêu thích...', 'string', CURRENT_TIMESTAMP),
    ('home_link_label', 'Trang chủ', 'string', CURRENT_TIMESTAMP),
    ('all_products_label', 'Tất cả', 'string', CURRENT_TIMESTAMP),
    ('sale_link_label', 'Sale tới 50%', 'string', CURRENT_TIMESTAMP),
    ('for_you_link_label', 'For You', 'string', CURRENT_TIMESTAMP),
    ('show_all_products_link', 'true', 'boolean', CURRENT_TIMESTAMP),
    ('show_sale_link', 'true', 'boolean', CURRENT_TIMESTAMP),
    ('show_for_you_link', 'true', 'boolean', CURRENT_TIMESTAMP),
    ('mobile_menu_eyebrow', 'WIND OF FALL', 'string', CURRENT_TIMESTAMP),
    ('mobile_menu_slogan', 'Tìm outfit cho cả gia đình', 'string', CURRENT_TIMESTAMP),
    ('mobile_support_text', 'Hỗ trợ tư vấn set đồ 1:1 qua hotline 1900 123 456', 'string', CURRENT_TIMESTAMP),
    ('hero_eyebrow', 'Bộ sưu tập mới / mặc đẹp mỗi ngày', 'string', CURRENT_TIMESTAMP),
    ('hero_title', 'Chọn nhanh outfit đẹp cho nam, nữ và trẻ em.', 'string', CURRENT_TIMESTAMP),
    ('hero_copy', 'Áo polo, sơ mi, váy, jeans và nhiều mẫu dễ mặc đã sẵn sàng để bạn mua ngay.', 'string', CURRENT_TIMESTAMP),
    ('hero_primary_label', 'Mua bộ sưu tập mới', 'string', CURRENT_TIMESTAMP),
    ('hero_primary_url', '/products', 'url', CURRENT_TIMESTAMP),
    ('hero_secondary_label', 'Xem khu sale', 'string', CURRENT_TIMESTAMP),
    ('hero_secondary_url', '/products?sale=true', 'url', CURRENT_TIMESTAMP),
    ('hero_stat_1_value', 'Từ 499K', 'string', CURRENT_TIMESTAMP),
    ('hero_stat_1_label', 'Freeship toàn quốc', 'string', CURRENT_TIMESTAMP),
    ('hero_stat_2_value', '30 ngày', 'string', CURRENT_TIMESTAMP),
    ('hero_stat_2_label', 'Đổi trả linh hoạt', 'string', CURRENT_TIMESTAMP),
    ('hero_stat_3_value', '24/7', 'string', CURRENT_TIMESTAMP),
    ('hero_stat_3_label', 'Hỗ trợ online', 'string', CURRENT_TIMESTAMP),
    ('show_home_categories', 'true', 'boolean', CURRENT_TIMESTAMP),
    ('show_home_new_products', 'true', 'boolean', CURRENT_TIMESTAMP),
    ('show_home_editorial', 'true', 'boolean', CURRENT_TIMESTAMP),
    ('show_home_best_sellers', 'true', 'boolean', CURRENT_TIMESTAMP),
    ('show_home_services', 'true', 'boolean', CURRENT_TIMESTAMP),
    ('home_new_products_limit', '10', 'int', CURRENT_TIMESTAMP),
    ('home_best_sellers_limit', '5', 'int', CURRENT_TIMESTAMP),
    ('home_categories_title', 'Mua sắm theo nhu cầu của bạn.', 'string', CURRENT_TIMESTAMP),
    ('home_categories_copy', 'Chọn nhanh theo nam, nữ và trẻ em để tìm đúng sản phẩm bạn cần.', 'string', CURRENT_TIMESTAMP),
    ('home_new_products_title', 'Hàng mới lên kệ hôm nay.', 'string', CURRENT_TIMESTAMP),
    ('home_best_sellers_title', 'Những mẫu được chọn nhiều nhất.', 'string', CURRENT_TIMESTAMP),
    ('home_editorial_title', 'Dễ mặc từ công sở đến cuối tuần.', 'string', CURRENT_TIMESTAMP),
    ('home_editorial_copy', 'Các nhóm sản phẩm được sắp theo những nhu cầu mặc thường ngày để bạn chọn nhanh hơn.', 'string', CURRENT_TIMESTAMP),
    ('popup_enabled', 'true', 'boolean', CURRENT_TIMESTAMP),
    ('popup_frequency_hours', '24', 'int', CURRENT_TIMESTAMP),
    ('popup_fallback_eyebrow', 'WIND OF FALL', 'string', CURRENT_TIMESTAMP),
    ('popup_fallback_button_label', 'Khám phá ngay', 'string', CURRENT_TIMESTAMP),
    ('footer_description', 'Thương hiệu thời trang everyday theo tinh thần hiện đại, gọn gàng và dễ mặc. Chúng tôi ưu tiên chất liệu, phom dáng và trải nghiệm mua sắm mượt mà trên mọi thiết bị.', 'string', CURRENT_TIMESTAMP),
    ('facebook_url', '#', 'url', CURRENT_TIMESTAMP),
    ('instagram_url', '#', 'url', CURRENT_TIMESTAMP),
    ('tiktok_url', '#', 'url', CURRENT_TIMESTAMP),
    ('zalo_url', '', 'url', CURRENT_TIMESTAMP),
    ('contact_hotline', '1900 123 456', 'string', CURRENT_TIMESTAMP),
    ('contact_email', 'info@windoffall.vn', 'string', CURRENT_TIMESTAMP),
    ('contact_address', '123 Nguyễn Huệ, Quận 1, TP.HCM', 'string', CURRENT_TIMESTAMP),
    ('opening_hours', 'Mở cửa 8:00 - 22:00 mỗi ngày', 'string', CURRENT_TIMESTAMP),
    ('copyright_text', '© 2026 WIND OF FALL. All rights reserved.', 'string', CURRENT_TIMESTAMP),
    ('newsletter_eyebrow', 'Newsletter', 'string', CURRENT_TIMESTAMP),
    ('newsletter_title', 'Nhập email để nhận ưu đãi và bộ sưu tập mới sớm hơn', 'string', CURRENT_TIMESTAMP),
    ('newsletter_copy', 'Cập nhật BST mới, voucher độc quyền và gợi ý phối đồ theo mùa.', 'string', CURRENT_TIMESTAMP),
    ('newsletter_button_label', 'Đăng ký ngay', 'string', CURRENT_TIMESTAMP),
    ('newsletter_success_text', 'Bạn đã đăng ký nhận tin khuyến mại thành công.', 'string', CURRENT_TIMESTAMP),
    ('payment_badges', '["COD","VNPay","MoMo","Visa"]', 'json', CURRENT_TIMESTAMP),
    ('service_shipping_title', 'Freeship đơn từ 499K', 'string', CURRENT_TIMESTAMP),
    ('service_shipping_copy', 'Thông tin ưu đãi rõ ràng ngay từ trang đầu để bạn chốt đơn nhanh hơn.', 'string', CURRENT_TIMESTAMP),
    ('service_return_title', 'Đổi trả trong 30 ngày', 'string', CURRENT_TIMESTAMP),
    ('service_return_copy', 'Yên tâm thử size và đổi mẫu nếu chưa thật sự phù hợp.', 'string', CURRENT_TIMESTAMP),
    ('service_consult_title', 'Hỗ trợ qua hotline và chat', 'string', CURRENT_TIMESTAMP),
    ('service_consult_copy', 'Dễ hỏi size, hỏi phối đồ và theo dõi đơn hàng khi cần.', 'string', CURRENT_TIMESTAMP),
    ('service_payment_title', 'Thanh toán rõ ràng', 'string', CURRENT_TIMESTAMP),
    ('service_payment_copy', 'COD, VNPay và MoMo hiển thị sớm để người mua dễ lựa chọn.', 'string', CURRENT_TIMESTAMP),
    ('free_shipping_min_amount', '500000', 'int', CURRENT_TIMESTAMP),
    ('return_window_days', '30', 'int', CURRENT_TIMESTAMP),
    ('policy_links', '[{"label":"Vận chuyển","url":"/policy/shipping"},{"label":"Đổi trả","url":"/policy/return"},{"label":"Thanh toán","url":"/policy/payment"},{"label":"Bảo mật thông tin","url":"/policy/privacy"}]', 'json', CURRENT_TIMESTAMP),
    ('seo_title', 'WIND OF FALL | Thời trang mỗi ngày', 'string', CURRENT_TIMESTAMP),
    ('meta_description', 'WIND OF FALL - mua sắm thời trang everyday cho nam, nữ và trẻ em.', 'string', CURRENT_TIMESTAMP),
    ('meta_keywords', 'thời trang, quần áo, wind of fall', 'string', CURRENT_TIMESTAMP),
    ('og_title', 'WIND OF FALL', 'string', CURRENT_TIMESTAMP),
    ('og_description', 'Thời trang everyday hiện đại, dễ mặc và dễ mua.', 'string', CURRENT_TIMESTAMP),
    ('og_image_url', '/favicon.png', 'image', CURRENT_TIMESTAMP),
    ('robots_index', 'true', 'boolean', CURRENT_TIMESTAMP),
    ('chat_enabled', 'true', 'boolean', CURRENT_TIMESTAMP),
    ('chat_title', 'WIND OF FALL', 'string', CURRENT_TIMESTAMP),
    ('chat_bot_name', 'WIND OF FALL', 'string', CURRENT_TIMESTAMP),
    ('chat_greeting', 'Xin chào! Tôi là trợ lý AI của WIND OF FALL.', 'string', CURRENT_TIMESTAMP),
    ('chat_prompt_text', 'Bạn cần hỗ trợ gì?', 'string', CURRENT_TIMESTAMP),
    ('chat_position', 'right', 'select', CURRENT_TIMESTAMP),
    ('default_web_email', 'nvuthanh4@gmail.com', 'string', CURRENT_TIMESTAMP),
    ('email_sender_name', 'WIND OF FALL', 'string', CURRENT_TIMESTAMP),
    ('support_email', 'support@windoffall.vn', 'string', CURRENT_TIMESTAMP),
    ('email_footer_text', 'Cảm ơn bạn đã đồng hành cùng WIND OF FALL.', 'string', CURRENT_TIMESTAMP),
    ('payment_window_hours', '24', 'int', CURRENT_TIMESTAMP),
    ('shipping_fee_amount', '30000', 'int', CURRENT_TIMESTAMP),
    ('payment_cod_enabled', 'true', 'boolean', CURRENT_TIMESTAMP),
    ('payment_vnpay_enabled', 'true', 'boolean', CURRENT_TIMESTAMP),
    ('payment_momo_enabled', 'true', 'boolean', CURRENT_TIMESTAMP),
    ('payment_reminder_text', 'Đơn hàng online cần thanh toán trong thời hạn quy định để được xử lý.', 'string', CURRENT_TIMESTAMP),
    ('jwt_expire_minutes', '60', 'int', CURRENT_TIMESTAMP),
    ('otp_expire_minutes', '10', 'int', CURRENT_TIMESTAMP),
    ('maintenance_mode', 'false', 'boolean', CURRENT_TIMESTAMP),
    ('maintenance_message', 'Website đang bảo trì, vui lòng quay lại sau.', 'string', CURRENT_TIMESTAMP)
ON DUPLICATE KEY UPDATE
    value_type = VALUES(value_type);
